--quiet --mode gtp < capture.tst > capture.out 
--quiet --mode gtp < connect.tst > connect.out
--quiet --mode gtp < connect_rot.tst > connect_rot.out
--quiet --mode gtp < connection.tst > connection.out
--quiet --mode gtp < connection_rot.tst > connection_rot.out
--quiet --mode gtp < cutstone.tst > cutstone.out
--quiet --mode gtp < dniwog.tst > dniwog.out
